artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/Decision_tree_mlruns/882213204614705365
creation_time: 1721483533747
experiment_id: '882213204614705365'
last_update_time: 1721483533747
lifecycle_stage: active
name: tree_exp
