artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/xgb_mlruns/766878027584291669
creation_time: 1721483912872
experiment_id: '766878027584291669'
last_update_time: 1721483912872
lifecycle_stage: active
name: xgb_exp
