artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/random_forest_mlruns/623720210708013733
creation_time: 1721483757674
experiment_id: '623720210708013733'
last_update_time: 1721483757674
lifecycle_stage: active
name: randomforest_exp
