artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/random_forest_mlruns/0
creation_time: 1721483757495
experiment_id: '0'
last_update_time: 1721483757495
lifecycle_stage: active
name: Default
