artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/logistic_mlruns/0
creation_time: 1721482255332
experiment_id: '0'
last_update_time: 1721482255332
lifecycle_stage: active
name: Default
