artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/xgb_mlruns/0
creation_time: 1721483912669
experiment_id: '0'
last_update_time: 1721483912669
lifecycle_stage: active
name: Default
