artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/logistic_mlruns/560003146134992080
creation_time: 1721482255903
experiment_id: '560003146134992080'
last_update_time: 1721482255903
lifecycle_stage: active
name: logistic_exp
